### ISSUE TITLE
Stage marked as finished while sub-processes still running

### ISSUE THREAD

**Issue by jehoshuapratama** [buihuukhoi/CREME#1]
I am just wondering that the top 3 icons are showing that there are still processes running right? But why this stage is marked as finished? Where can I make sure that these processes are already finished?

![Issue1](https://user-images.githubusercontent.com/50482705/115570415-ac35f480-a2f0-11eb-92bf-e0215451ccc0.PNG)

**Comment by buihuukhoi** [comment]
The first two icons are correct because some processes need to run through all stages of the attack scenario.
However, the third icon is not correct; bots only can be found once. I updated the icon to the finished icon.
If you see the "Finished Stage" message and green background, it means the stage is finished.

**Comment by buihuukhoi** [comment]
I have fixed this it: 3ee367b7229e076727e9b9b645d3c552fc058f08
